config/routes.rb
Rails.application.routes.draw do
  resources :devices

  get 'history/index'

  get 'status/display'

  get 'status/index'

  get 'status/checkout'

  get 'status/checkin'

  put 'status/take'
  patch 'status/take'

  put 'status/return'
  patch 'status/return'

  root 'status#display'

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_one :status, :foreign_key => :code
  has_many :histories
  validates :os, :model, :code, presence: true
  validates :code, uniqueness: true
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :device
  validates :code, :holder, :timeout, :timein, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :devices, :foreign_key => :code
  validates :code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "secret"

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
    @status = Status.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @status = Status.new(code: params[:device][:code])

    respond_to do |format|
      Device.transaction do
        begin
          if @device.save && @status.save
            format.html { redirect_to @device, notice: 'Device was successfully created.' }
            format.json { render :show, status: :created, location: @device }
          else 
            format.html { render :new }
            format.json { render json: @device.errors, status: :unprocessable_entity }
          end
        rescue
        end
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      Device.transaction do
        if @device.update(device_params) && @status.update(code: params[:device][:code])
          format.html { redirect_to @device, notice: 'Device was successfully updated.' }
          format.json { render :show, status: :ok, location: @device }
        else
          format.html { render :edit }
          format.json { render json: @device.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    Device.transaction do
      @device.destroy
      @status.destroy
    end
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
      @status = Status.find_by(code: @device.code)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:os, :model, :code)
    end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "secret"
  def index
    @records = History.all
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  before_action :set_status, only: [:checkin, :checkout, :take, :return]
  http_basic_authenticate_with name: "admin", password: "secret", except: :display

  def display
    @statuses = Status.joins('LEFT OUTER JOIN devices ON devices.code = statuses.code').select("statuses.available, devices.*")
  end

  def index
    @statuses = Status.joins('LEFT OUTER JOIN devices ON devices.code = statuses.code').select("statuses.*, devices.*")
  end

  # GET /status/checkout
  def checkout
  end

  # GET /status/checkin
  def checkin
  end

  # PUT /status/1
  def take
    respond_to do |format|
      if @statu.update(holder: params[:status][:holder], time: params[:status][:time], available: false)
        format.html { redirect_to '/status/index', notice: 'Device has been checked out.' }
        format.json { render :index, status: :ok, location: @statu }
      else
        format.html { render :checkout }
        format.json { render json: @statu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /status/1
  # update history model
  def return
    record = History.new(code: params[:status][:code], holder: params[:status][:holder], timeout: @statu.time, timein: params[:status][:time])

    respond_to do |format|
      Status.transaction do
        if @statu.update(holder: "", time: "", available: true) && record.save
          format.html { redirect_to '/status/index', notice: 'Device has been returned.' }
          format.json { render :show, status: :ok, location: @statu }
        else
          format.html { render :checkout }
          format.json { render json: @statu.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    def set_status
      @statu = Status.find_by(code: params[:code]) || Status.find_by(code: params[:status][:code])
    end

    def status_params
      params.require(:status).permit(:code, :holder, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :os %><br>
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<div class="container">
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>
</div>

app/views/devices/index.html.erb
<div class="container">
<h1>Listing devices</h1>
<table class="table">
  <thead>
    <tr>
      <th>OS</th>
      <th>Model</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.os %></td>
        <td><%= device.model %></td>
        <td><%= device.code %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Device', new_device_path %>

</div>

app/views/devices/new.html.erb
<div class="container">
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>
</div>

app/views/devices/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>OS:</strong>
  <%= @device.os %>
</p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Code:</strong>
  <%= @device.code %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>
</div>

app/views/history/index.html.erb
<div class="container">
<h1>History</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Holder</th>
      <th>Time out</th>
      <th>Time in</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.code %></td>
        <td><%= record.holder %></td>
        <td><%= record.timeout %></td>
        <td><%= record.timein %></td>


      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Device Inventory</a>
	<ul class="nav navbar-nav navbar-right">
	  <li><a href="/status/index" target="_blank">Check out</a></li>
	</ul>
      </div>
    </div>
  </nav>
</div>

<%= yield %>

<hr />

<footer class="footer">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
      <li id="admn"><a>Admin links:</a></li>
      <li><a href="/status/index" target="_blank">Check out</a></li>
      <li><a href="/devices" target="_blank">Devices</a></li>
      <li><a href="/history/index" target="_blank">History</a></li>
    </ul>
  </div>
</footer>

</body>
</html>

app/views/status/checkin.html.erb
<div class="container">
<h1>Returning device <%= @statu.code %></h1>

<%= form_for(@statu, url: {action: "return"}) do |f| %>

  <div class="field">
    <%= f.label 'Name' %><br>
    <%= f.text_field :holder, readonly: true %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time, required: true%>
  </div>
  <%= f.hidden_field :code, :value => @statu.code %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', '/status/index' %>
</div>

app/views/status/checkout.html.erb
<div class="container">
<h1>Checking out device</h1>

<%= form_for(@statu, url: {action: "take"}) do |f| %>

  <div class="field">
    <%= f.label 'Name' %><br>
    <%= f.text_field :holder, required: true %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time, required: true%>
  </div>
  <%= f.hidden_field :code, :value => @statu.code %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', '/status/index' %>
</div>

app/views/status/display.html.erb
<div class="container">
<h1>Devices</h1>

<table class="table">
  <thead>
    <tr>
      <th>OS</th>
      <th>Model</th>
      <th>Code</th>
      <th>Available?</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |device| %>
      <tr>
        <td><%= device.os %></td>
        <td><%= device.model %></td>
        <td><%= device.code %></td>
	<td><%= device.available%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/status/index.html.erb
<div class="container">
<h1>Devices</h1>

<table class="table">
  <thead>
    <tr>
      <th>OS</th>
      <th>Model</th>
      <th>Code</th>
      <th>Available?</th>
      <th>Holder</th>
      <th>Time</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |device| %>
      <tr>
        <td><%= device.os %></td>
        <td><%= device.model %></td>
        <td><%= device.code %></td>
	<td><%= device.available%></td>
	<td><%= device.holder %></td>
	<td><%= device.time %></td>
	<td>
	  <% if device.available %>
            <%= link_to 'Check out', {controller: "status", action: "checkout", code: device.code} %>
	  <% else %>
            <%= link_to 'Check in', {controller: "status", action: "checkin", code: device.code} %>
	  <% end %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>